# Projeto 2 - Extração e Análise de Métricas em Redes Sociais

Total: 0,5 Ponto

Para executar as análises, não esqueça de instalar as bibliotecas necessárias em requirements.txt

No terminal...
```bash
pip install -r requirements.txt
```
(Verifique se está na pasta do mesmo arquivo requirements.txt. Para descobrir, digite `dir` e veja se o arquivo aparece na lista)

In [1]:
aluno = input('Qual o nome do(s) aluno(s)?:   ')
print(f'Aluno(s) {aluno} registrado(s) com sucesso!')

Aluno(s)  registrado(s) com sucesso!

### 0) Preparação

Escolha uma base da pasta "bases" que se inicie com "tktk_" e termine com ".csv", e abra-a. Caso queira utilizar uma base própria, seja do Instagram ou TikTok, sinta-se à vontade. Atente que, caso a base escolhida não seja uma da pasta, você precisará tratá-la adequadamente. Abaixo, segue um código de exemplo para tratar uma base do Tiktok oriunda do Zeeschuimer. 

```python
colunas_desejadas = ['id', 'desc', 'challenges', 'createTime', 'video.duration', 'video.cover', 'author.id',
                'author.nickname', 'author.uniqueId','author.verified', 'music.title', 'authorStats.followingCount',
                'authorStats.followerCount', 'authorStats.heartCount', 'authorStats.videoCount',
                'authorStats.diggCount', 'authorStats.heart', 'statsV2.collectCount', 'statsV2.commentCount',
                'statsV2.diggCount', 'statsV2.playCount', 'statsV2.shareCount']
df = df[colunas_desejadas]
df['createdAt'] = df['createTime'].apply(lambda x: pd.Timestamp(x, unit='s'))

def preenche_url(item):
    return f"https://www.tiktok.com/@{item['author.uniqueId']}/video/{item['id']}"

df['url'] = df.apply(preenche_url, axis=1)
df['statsV2.diggCount'] = df['statsV2.diggCount'].astype(float)
df['statsV2.playCount'] = df['statsV2.playCount'].astype(float)
df['statsV2.shareCount'] = df['statsV2.shareCount'].astype(float)
df['statsV2.commentCount'] = df['statsV2.commentCount'].astype(float)
df['statsV2.collectCount'] = df['statsV2.collectCount'].astype(float)

def get_hashtags(lista):
    resultado = []
    try:
        for item in lista:
            resultado.append(item['title'])
        return resultado
    except:
        return resultado
  
df['hashtags'] = df['challenges'].apply(get_hashtags)
```

As bases do TikTok disponíveis na pasta "bases" são:

- tktk_base1.csv
- tktk_base2.csv
- tktk_base3.csv

### Lembrete: todos os gráficos gerados tem que ser LEGÍVEIS, ou seja, interpretáveis. Faça escolhas razoáveis para que os gráficos estejam de acordo. 

### 1) Abertura da base e estatísticas gerais (0,1)

Abra a base escolhida, exiba as primeiras 15 linhas, e mostre, para **cada variável numérica** da base, a contagem de linhas, a média, o mínimo, o percentil 25%, a mediana (percentil 50%), o percentil 75%, o máximo e o desvio padrão. (0,05)

Abaixo do código, faça um comentário interpretativo sobre o que você observou nos resultados. (0,05)

In [3]:
import pandas as pd

df= pd.read_csv('tktk_base1.csv')
display(df.head(15))
display(df.describe())

,AIGCDescription,CategoryType,backendSourceEventTracking,challenges,collected,contents,createTime,desc,digged,diversificationId,...,moderationAigcLabelType,repostList,isECVideo,author.roomId,brandOrganicType,event.event_id,event.event_start_time,event.has_subscribed,event.title,duetInfo.duetFromId
0,NaN,101,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,[{'desc': 'foi preso #felca #felcacamp #edit #...,1756141425,foi preso #felca #felcacamp #edit #fyp @Felca ...,False,10045.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,104,NaN,NaN,False,[{'desc': 'o FELCA de um jeito que a web nunca...,1745183232,o FELCA de um jeito que a web nunca viu. @Felca,False,10000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,101,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,[{'desc': '#felca #felcaedit #altashoras #pole...,1755426372,#felca #felcaedit #altashoras #polemica #indir...,False,10088.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,119,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,"[{'desc': '#Hytalo #kamilinha #Felca', 'textEx...",1755528190,#Hytalo #kamilinha #Felca,False,10005.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,120,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,[{'desc': 'Felca contando pra Cela que ele é X...,1749583504,Felca contando pra Cela que ele é XYX . . . #f...,False,10075.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,104,NaN,NaN,False,NaN,1752634484,NaN,False,10003.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,0,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,"[{'desc': '@Felca @Yasmin Yassine ', 'textExtr...",1754238995,@Felca @Yasmin Yassine #felca #felcacamp #yas...,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,120,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,"[{'desc': 'Felca> kamilinha '}, {'desc': 'Felc...",1754880091,Felca> kamilinha Felca passou o carro no hyta...,False,10075.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,0,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,[{'desc': 'ROSAS 🤣 #felca #felcalive #felcaedi...,1694391397,ROSAS 🤣 #felca #felcalive #felcaedit #memes,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,104,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,"[{'desc': 'kkkkkk '}, {'desc': ''}, {'desc': '...",1751683686,kkkkkk #felca #fyp #beamon,False,10003.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,114,NaN,[{'coverLarger': 'https://p16-amd-va.tiktokcdn...,False,[{'desc': 'Esquerda e Felca - uma análise da s...,1755386959,Esquerda e Felca - uma análise da situação atu...,False,10087.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,104,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,[{'desc': 'A filha perdida do Felca😂😱 #felca #...,1755382946,A filha perdida do Felca😂😱 #felca #felcacamp #...,False,10003.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,0,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,[{'desc': 'Felca fala sobre o assunto de Hytal...,1755293445,Felca fala sobre o assunto de Hytalo Santos #f...,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,104,NaN,"[{'coverLarger': '', 'coverMedium': '', 'cover...",False,[{'desc': 'a diferença de tamanho kkkkkkkkkkkk...,1744241400,a diferença de tamanho kkkkkkkkkkkk #felca #fe...,False,10003.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,0,NaN,NaN,False,[{'desc': 'Os problemas do vídeo do Fleca! Cla...,1755017215,Os problemas do vídeo do Fleca! Claro que não ...,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,AIGCDescription,CategoryType,backendSourceEventTracking,createTime,diversificationId,duetDisplay,id,itemCommentStatus,stitchDisplay,author.UserStoryStatus,...,poi.typeCode,aigcLabelType,moderationAigcLabelType,isECVideo,author.roomId,brandOrganicType,event.event_id,event.event_start_time,event.title,duetInfo.duetFromId
count,0.0,603.000000,0.0,6.030000e+02,395.000000,603.0,6.030000e+02,603.0,603.0,603.000000,...,0.0,7.00000,1.0,3.0,3.000000e+00,1.0,2.000000e+00,2.0,0.0,1.000000e+00
mean,NaN,72.945274,NaN,1.747213e+09,10044.048101,0.0,7.504219e+18,0.0,0.0,0.116086,...,NaN,1.00000,1.0,1.0,7.542877e+18,1001.0,7.540411e+18,0.0,NaN,7.221287e+18
std,NaN,53.327285,NaN,1.652323e+07,33.531487,0.0,7.096643e+16,0.0,0.0,0.320594,...,NaN,0.57735,NaN,0.0,0.000000e+00,NaN,0.000000e+00,0.0,NaN,NaN
min,NaN,0.000000,NaN,1.637546e+09,10000.000000,0.0,7.033205e+18,0.0,0.0,0.000000,...,NaN,0.00000,1.0,1.0,7.542877e+18,1001.0,7.540411e+18,0.0,NaN,7.221287e+18
25%,NaN,0.000000,NaN,1.747045e+09,10005.000000,0.0,7.503503e+18,0.0,0.0,0.000000,...,NaN,1.00000,1.0,1.0,7.542877e+18,1001.0,7.540411e+18,0.0,NaN,7.221287e+18
50%,NaN,104.000000,NaN,1.755007e+09,10046.000000,0.0,7.537698e+18,0.0,0.0,0.000000,...,NaN,1.00000,1.0,1.0,7.542877e+18,1001.0,7.540411e+18,0.0,NaN,7.221287e+18
75%,NaN,117.000000,NaN,1.755474e+09,10075.000000,0.0,7.539702e+18,0.0,0.0,0.000000,...,NaN,1.00000,1.0,1.0,7.542877e+18,1001.0,7.540411e+18,0.0,NaN,7.221287e+18
max,NaN,120.000000,NaN,1.756196e+09,10096.000000,0.0,7.542806e+18,0.0,0.0,1.000000,...,NaN,2.00000,1.0,1.0,7.542877e+18,1001.0,7.540411e+18,0.0,NaN,7.221287e+18

> Comentário:

### 2) Qual a média e a mediana dos likes, comentários, compartilhamentos e plays, por autor? (0,1)

Calcule a média e a mediana dos likes, comentários, compartilhamentos e plays, por autor. (0,05)

Abaixo do código, faça um comentário interpretativo sobre o que você observou nos resultados. (0,05)

In [ ]:
df_limpo= df['author.nickname','authorStats.heartCount','stats.commentCount']

> Comentário:

### 3) Qual a média da proporção, por usuário, de comentários por like? Ou seja, a cada like, quantos comentários cada usuário recebe? Organize por quem engaja mais (nesse caso, quem tem mais comentários por like) usando o método .sort_values(). (0,1) 

Calcule a proporção de comentários por like em cada vídeo, e depois, a média dessa proporção por autor. Organize por ordem decrescente a partir dessa métrica criada. (0,05)

Abaixo do código, faça um comentário interpretativo sobre o que você observou nos resultados. (0,05)

> Comentário:

### 4) Crie um gráfico de barras que mostre a quantidade de vídeos por autor. (0,1)

Crie um gráfico de barras que mostre a quantidade de vídeos por autor, utilizando o seaborn ou matplotlib (0,05)

Abaixo do gráfico, faça um comentário interpretativo sobre o que você observou nos resultados. (0,05)

> Comentário:

### 5) Faça uma nuvem de palavras com as 100 hashtags mais utilizadas na base. (0,1)

Faça uma nuvem de palavras com as 100 hashtags mais utilizadas na base. (0,05)

Abaixo do gráfico, faça um comentário interpretativo sobre o que você observou nos resultados. (0,05)

> Comentário:

# Extra: 0,1

Identifique o tema do dataset com base nas análises anteriores.

# Resposta: